com/views/auth.py
from flask import Blueprint, render_template, redirect, url_for, flash, session, current_app
from flask_login import login_user, logout_user, current_user
from com.forms.auth import LoginForm
from com.plugins import db
from com.models import SysUser, SysLog, SysMenu
import uuid, jpype
bp_auth = Blueprint('auth', __name__)
@bp_auth.route('/login', methods=['GET', 'POST'])
def login():
    '''
    系统登录
    :return:
    '''
    #interfaces current_user.is_authenticated:
        #return redirect(url_for('main.index'))
    form = LoginForm()
    if form.validate_on_submit():
        user_id = form.user_id.data
        user_pwd = form.user_pwd.data
        # print('User id is %s, password is %s' %(user_id, user_pwd))
        user = SysUser.query.filter_by(user_id=user_id.lower()).first()
        if user:
            if user.active:
                if user.is_ad:
                    # AD验证
                    jvm_path = current_app.config['JVM_PATH']
                    ad_jar_path = current_app.config['AD_JAR_PATH'] + '\\ad.auth.module-1.0.jar'
                    # 如果已启动，捕捉异常后跳过启动JVM
                    try:
                        jpype.startJVM(jvm_path, '-ea', '-Djava.class.path=' + ad_jar_path)
                    except:
                        pass
                    jpype.java.lang.System.out.println('Hello world from JAVA!!!')
                    package = jpype.JPackage('DSGAuthPkg')
                    auth = package.Auth("authsj.corp.doosan.com", "dsg\\" + user_id, user_pwd)
                    validate_ok = auth.validateUser(user_id, user_pwd)
                else:
                    validate_ok = user.validate_password(user_pwd)
                if validate_ok:
                    login_user(user, True)
                    log = SysLog(id=uuid.uuid4().hex, url='auth.login', operation='登录系统', user=user)
                    db.session.add(log)
                    db.session.commit()
                    # 类GMES跳转
                    # return redirect(url_for('main.to_function'))
                    # 传统布局使用以下跳转
                    modules = current_user.authed_modules
                    if modules:
                        for module in modules:
                            print('Module name : ', module.name)
                        module_menu = current_user.authed_menus
                        for module, menu in module_menu.items():
                            print('Module id : ', module, ', menus : ', menu)
                        module_id = current_user.authed_modules[0].id
                        return redirect(url_for('main.to_uri', module_id=module_id, menu_id=current_user.authed_menus[module_id][0].id))
                    else:
                        flash('该用户没有分配任何系统权限，请联系管理员！')
                        return render_template('main/not-authed.html')
                else:
                    flash('密码错误！')
            else:
                flash('用户已停用！')
        else:
            flash('用户不存在！')
    return render_template('auth/sign_in.html', form=form)
@bp_auth.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('.login'))

com/views/main.py
from flask import Blueprint, render_template, session, redirect, url_for, request, flash
from flask_login import login_required, current_user
from com.plugins import db
from com.models import SysMenu
bp_main = Blueprint('main', __name__)
@bp_main.route('/index')
@login_required
def index():
    '''
    跳转主页，暂未使用
    :return:
    '''
    print('Current module main index : ', session['active_module'])
    print('Current menu main index : ', session['active_menu'])
    session.pop('active_module', None)
    session.pop('active_menu', None)
    return render_template('main/index.html')
'''
点击导航及菜单项执行页面跳转逻辑处理
:return:
'''
@bp_main.route('/redirect_uri')
@login_required
def redirect_uri():
    '''
        获取当前模块ID
        逻辑：
        1. 如果module_id传递过来，取传递过来的module_id
        2. 没有传递取session中的active_module_id
        3. session没有取用户授权模块清单中的第一个模块的ID
    '''
    module_id = request.args.get('module_id') if request.args.get('module_id') else session['active_module'] if session['active_module'] else current_user.authed_modules[0].id
    '''
        获取当前菜单ID
        逻辑：
        1. 如果menu_id传递过来，取传递过来的menu_id
        2. 如果没有传递，取当前模块下菜单清单中第一个菜单ID
    '''
    menu_id = request.args.get('menu_id') if request.args.get('menu_id') else current_user.authed_menus[module_id][0].id
    return redirect(url_for('.to_uri', module_id=module_id, menu_id=menu_id))
'''
执行跳转至对应的功能画面
'''
@bp_main.route('/to_uri/<module_id>/<menu_id>')
@login_required
def to_uri(module_id, menu_id):
    print('Parameter module id is : ', module_id)
    print('Parameter menu id is : ', menu_id)
    session['active_module'] = module_id    # 用于head导航栏栏nav active判断
    session['active_menu'] = menu_id        # 用于左侧菜单menu active判断
    menu = SysMenu.query.get_or_404(menu_id)
    print('Menu url is : ', menu.url)
    print('Menu name is : ', menu.name)
    return redirect(url_for(menu.url))
    # return render_template('main/index.html')
@bp_main.route('/to_function', methods=['GET', 'POST'])
@login_required
def to_function():
    # 使用过的菜单项
    used_menus = current_user.used_menus
    # 已授权菜单ID数据:code list
    authed_menus = current_user.menus
    for menu in used_menus:
        if menu.code not in authed_menus:
            current_user.used_menus.remove(menu)
            db.session.commit()
    # 重新获取已使用的菜单项
    used_menus = current_user.used_menus
    if request.method == 'POST':
        menu_code = request.form['menu_code']
        menu = SysMenu.query.filter_by(code=menu_code.upper()).first()
        if menu:
            # 判断是否具有权限
            if menu_code.upper() in current_user.menus:
                session['active_module'] = menu.module.id
                session['active_menu'] = menu.id
                if menu not in current_user.used_menus:
                    current_user.used_menus.append(menu)
                    db.session.commit()
                return redirect(url_for(menu.url))
            else:
                flash('您没有该功能画面权限，请联系管理员！')
        else:
            flash('功能代码错误,没有对应的画面！')
    return render_template('main/home.html', used_menus=used_menus)

com/templates/_footer.html
<nav class="navbar fixed-bottom navbar-light bg-light justify-content-center">
    <small>CopyRight:&copy;HyunDai Doosan Infracore China 2022</small>
</nav>

com/templates/_header.html
{% from 'bootstrap/nav.html' import render_nav_item with context %}
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  {# 跳转主页，暂不使用 #}
  {#<a class="navbar-brand" href="{{url_for('main.index')}}"><i class="bi bi-laptop"></i>&nbsp;&nbsp;IT&nbsp;统合管理系统</a>#}
  <a class="navbar-brand" href="#"><i class="bi bi-laptop" style="font-size:1.5em;"></i></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarScroll" aria-controls="navbarScroll" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarScroll">
    <ul class="navbar-nav mr-auto my-2 my-lg-0 navbar-nav-scroll" style="max-height: 100px;">
      {% if current_user.authed_modules %}
        {% for module in current_user.authed_modules %}
          <li class="nav-item">
              <a class="nav-link btn btn-outline-info {% if session.get('active_module') == module.id%}active{% endif %}" href="{{url_for('main.redirect_uri', module_id=module.id)}}">{{module.name}}</a>
          </li>&nbsp;&nbsp;&nbsp;&nbsp;
        {% endfor %}
      {% endif %}
    </ul>
    <div class="d-flex">
        {% if current_user.is_authenticated %}
            <h5 class="text-secondary"><i class="bi bi-person"></i>&nbsp;{{current_user.user_name}}</h5>&nbsp;&nbsp;&nbsp;&nbsp;
            <a class="btn btn-outline-success btn-sm" title="登出" href="{{url_for('auth.logout')}}"><i class="bi bi-box-arrow-right"></i></a>
        {% endif %}
    </div>
  </div>
</nav>

com/templates/_header1.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="{{url_for('main.to_function')}}"><i class="bi bi-laptop"  style="font-size:1em;"></i></a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class = "container-fluid">
        <form class="form-inline" action="{{url_for('main.to_function')}}" method="post">
            <div class="form-group">
                <input type="hidden" value="{{csrf_token()}}" id="csrf_token" name="csrf_token">
                <input type="text" name="menu_code" class="form-control form-control-sm" placeholder="请输入功能代码" required>
            </div>&nbsp;&nbsp;
            <button type = "submit" class="btn btn-light btn-sm">GO!</button>
        </form>
        <div class="row text-right">
            {% if current_user.is_authenticated %}
                <div class="col-12">
                    <span class="text-secondary"><i class="bi bi-person"></i>&nbsp;{{current_user.user_name}}</span>&nbsp;&nbsp;
                    <a class="btn btn-outline-success btn-sm" title="登出" href="{{url_for('auth.logout')}}"><i class="bi bi-box-arrow-right"></i></a>
                </div>
            {% endif %}
        </div>
    </div>
</nav>

com/templates/_menus.html
{% set active_module = session.get('active_module') %}
{% set active_menu = session.get('active_menu') %}
{% set module_menus = current_user.authed_menus %}
{% set menus = module_menus[active_module] %}
{% if menus %}
<div class="list-group list-group-flush">
    {% for menu in menus%}
        <a href="{{url_for('main.redirect_uri', menu_id=menu.id)}}" class="list-group-item list-group-item-action"  {% if session.get('active_menu') == menu.id%}style="font-size: 1.1rem; color: cornflowerblue;"{% endif %}>
            <i class="{{menu.icon}}"></i>&nbsp;&nbsp;{{menu.name}}
        </a>
    {% endfor %}
</div>
{% else %}
<h3>There are no menus!!!</h3>
{% endif %}

com/templates/base.html
<!DOCTYPE html>
<html lang="en">
{# 显式使用with context引入宏函数文件 #}
{% from 'macros/_macro.html' import static_file, current_location with context %}
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{%block title %}IT资产管理系统{% endblock %}</title>
    {# 导入静态文件 #}
    {% block static %}
    {{static_file('icon', 'images/icon/sys.ico')}}
    {{static_file('css', 'css/bootstrap.min.css')}}
    {{static_file('css', 'css/bootstrap-icons.css')}}
    {{static_file('css', 'css/jquery-confirm.min.css')}}
    {{static_file('css', 'css/all.min.css')}}
    {{static_file('js', 'js/jquery-3.6.0.min.js')}}
    {#static_file('js', 'js/popper.min.js')#}
    {#static_file('js', 'js/bootstrap.min.js')#}
    {{static_file('js', 'js/bootstrap.bundle.min.js')}}
    {{static_file('js', 'js/jquery-confirm.min.js')}}
    {% endblock %}
    <!-- 生成执行时间渲染函数 -->
    {# moment.include_moment(local_js=url_for('static',filename='js/moment/moment-with-locales.js')) #}
    <!-- 设置自动识别显示语言 -->
    {# moment.locale(auto_detect=True) #}
    {# --------- 引入子页面自己的css文件 --------- #}
    {% block link %}{% endblock %}
    {# --------- 引入子页面自己的JavaScript文件 --------- #}
    {% block scripts %}{% endblock %}
    {# --------- 编写子页面自己的css样式 --------- #}
    {% block style %}{% endblock %}
</head>
<body>
<header>{% block header %}{% include '_header.html' %}{% endblock %}</header>
<main>
{% block main %}
    <div class="container-fluid" style="margin-top:10px;">
    <div class="row">
        <div class="col-2">{% include('_menus.html') %}</div>
        <div class="col-10">
            {% block content%}{% endblock %}
        </div>
    </div>
</div>
{% endblock %}
</main>
{#<footer>{% block footer %}{% include '_footer.html' %}{% endblock %}</footer>#}
<script>
{% block script %}
var csrf_token = "{{ csrf_token() }}"                   //CSRF令牌
$(function(){
    //ajax设置统一添加csrf验证
    $.ajaxSetup({
        beforeSend: function (xhr, settings) {
            if (!/^(GET|HEAD|OPTIONS|TRACE)$/i.test(settings.type) && !this.crossDomain) {
                xhr.setRequestHeader('X-CSRFToken', csrf_token);
            }
        }
    })
})
function init_date(id){
    $('#'+id).datepicker({
        weekStart: 1,
        autoclose: true,
        daysOfWeekHighlighted: "0,6",
        format: "yyyy-mm-dd",
        language: "zh-CN"
    })
}
{% endblock %}
</script>
</body>
</html>

com/templates/base1.html
<!DOCTYPE html>
<html lang="en">
{# 显式使用with context引入宏函数文件 #}
{% from 'macros/_macro.html' import static_file, current_location with context %}
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{%block title %}IT资产管理系统{% endblock %}</title>
    {# 导入静态文件 #}
    {% block static %}
    {{static_file('icon', 'images/icon/sys.ico')}}
    {{static_file('css', 'css/bootstrap.min.css')}}
    {{static_file('css', 'css/bootstrap-icons.css')}}
    {{static_file('css', 'css/jquery-confirm.min.css')}}
    {{static_file('css', 'css/all.min.css')}}
    {{static_file('js', 'js/jquery-3.6.0.min.js')}}
    {#static_file('js', 'js/popper.min.js')#}
    {#static_file('js', 'js/bootstrap.min.js')#}
    {{static_file('js', 'js/bootstrap.bundle.min.js')}}
    {{static_file('js', 'js/jquery-confirm.min.js')}}
    {% endblock %}
    <!-- 生成执行时间渲染函数 -->
    {# moment.include_moment(local_js=url_for('static',filename='js/moment/moment-with-locales.js')) #}
    <!-- 设置自动识别显示语言 -->
    {# moment.locale(auto_detect=True) #}
    {# --------- 引入子页面自己的css文件 --------- #}
    {% block link %}{% endblock %}
    {# --------- 引入子页面自己的JavaScript文件 --------- #}
    {% block scripts %}{% endblock %}
    {# --------- 编写子页面自己的css样式 --------- #}
    {% block style %}{% endblock %}
</head>
<body>
<header>{% block header %}{% include '_header.html' %}{% endblock %}</header><br>
<main>
{% block main %}
<div class="container-fluid">
{% block content%}{% endblock %}
</div>
{% endblock %}
</main>
<footer>{% block footer %}{% include '_footer.html' %}{% endblock %}</footer>
<script>
{% block script %}
var csrf_token = "{{ csrf_token() }}"                   //CSRF令牌
$(function(){
    //ajax设置统一添加csrf验证
    $.ajaxSetup({
        beforeSend: function (xhr, settings) {
            if (!/^(GET|HEAD|OPTIONS|TRACE)$/i.test(settings.type) && !this.crossDomain) {
                xhr.setRequestHeader('X-CSRFToken', csrf_token);
            }
        }
    })
})
function init_date(id){
    $('#'+id).datepicker({
        weekStart: 1,
        autoclose: true,
        daysOfWeekHighlighted: "0,6",
        format: "yyyy-mm-dd",
        language: "zh-CN"
    })
}
{% endblock %}
</script>
</body>
</html>